package com.schegolevalex.bot.reminderbot.state;

public enum State {
    ADD_REMINDER_DATE,
    ADD_REMINDER_TEXT,
    ADD_REMINDER_TIME,
    AWAIT_START,
    CHOOSE_FIRST_ACTION,
    CONFIRM_DELETE_REMINDER,
    DELETE_REMINDER,
    SUCCESSFUL_ADDITION,
    EDIT_REMINDER_TEXT,
    EDIT_REMINDER_DATE,
    EDIT_REMINDER_TIME,
    WATCH_REMINDERS,
    WRONG_INPUT,
    WRONG_INPUT_DATE,
    WRONG_INPUT_TIME,
    SUCCESSFUL_DELETION,
    SUCCESSFUL_EDITING,
    SHOW_REMINDER, WATCH_REMINDER
}
