package com.schegolevalex.bot.reminderbot.state;

public enum State {
    ADD_REMINDER_DATE,
    ADD_REMINDER_TEXT,
    ADD_REMINDER_TIME,
    AWAIT_START,
    CHOOSE_FIRST_ACTION,
    DELETE_REMINDER,
    SUCCESSFUL_ADDITION,
    EDIT_REMINDER,
    WATCH_REMINDERS,
    WRONG_INPUT,
    WRONG_INPUT_DATE,
    WRONG_INPUT_TIME,
    WATCH_REMINDER
}
